
import Nombre from "@/components/Nombre";
import "./globals.css";
import Link from "next/link";
import ContextoProvider from "@/components/context";
import AccountCircleIcon from '@mui/icons-material/AccountCircle';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

   


  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-gray-500 via-blue-700 to-blue-800 h-screen text-white ">
      
        <ContextoProvider>
        <nav className="bg-opacity-60 w-full flex flex-row  items-center justify-between gap-5 bg-gray-800 p-2">
          <div className="flex flex-row gap-3 px-2 items-center">
            <AccountCircleIcon style={{fontSize:34}}></AccountCircleIcon>
          <Nombre>

          </Nombre>
          </div>
          <div className="h-max p-1 flex flex-col md:flex-row gap-3">
          <Link className="border-b p-3 rounded-xl hover:text-zinc-400 hover:border-zinc-400" href="/create" >Crear Tarea</Link>
          <Link className="border-b p-3 rounded-xl hover:text-zinc-400 hover:border-zinc-400" href="/">Lista de tareas</Link>
          <Link className="border-b p-3 rounded-xl hover:text-zinc-400 hover:border-zinc-400" href="/login">Cambiar cuenta</Link>
          </div>
        </nav>
        <div className="w-full flex flex-col gap-3 items-center justify-center mt-2">
        {children}
        </div>
        </ContextoProvider>
      </body>

    </html>
  );
}
